version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports: 
      - 5432:5432
  
  user_app:
    build:
      context: ./
      network: host
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:5432/postgres"
    ports: 
      - 8000:8000
    depends_on:
      - postgres